# Deep Neural Network in TensorFlow

In this notebook, we improve on our [intermediate neural net](https://github.com/jonkrohn/DLTFpT/blob/master/notebooks/intermediate_net_in_tensorflow.ipynb) by incorporating the theory we've covered since.

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jonkrohn/DLTFpT/blob/master/notebooks/deep_net_in_tensorflow.ipynb)

#### Load dependencies

In [1]:
import tensorflow
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout # new! #it is used to prevent overfitting, works by hiding some of the neurons during training
from tensorflow.keras.layers import BatchNormalization # new! #it is used to normalize the input layer by adjusting and scaling the activations
from tensorflow.keras.optimizers import SGD
from matplotlib import pyplot as plt

#### Load data

In [2]:
(X_train, y_train), (X_valid, y_valid) = mnist.load_data()

#### Preprocess data

In [5]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_valid = X_valid.reshape(10000, 784).astype('float32')

In [6]:
X_train /= 255
X_valid /= 255

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
n_classes = 10
y_train = to_categorical(y_train, n_classes) # one-hot encoding
print(y_train)
y_valid = to_categorical(y_valid, n_classes)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


#### Design neural network architecture

In [9]:
model = Sequential()

model.add(Dense(64, activation='relu', input_shape=(784,)))
model.add(BatchNormalization())

model.add(Dense(64, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(64, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2)) #new! #it is used to prevent overfitting, works by hiding some of the neurons during training #added here  because there might be a chance that some features being memorised here are specific to the training data, only 0.2 because we didn't see a lot of overfitting before.

#output layer
model.add(Dense(10, activation='softmax'))

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                50240     
                                                                 
 batch_normalization (Batch  (None, 64)                256       
 Normalization)                                                  
                                                                 
 dense_1 (Dense)             (None, 64)                4160      
                                                                 
 batch_normalization_1 (Bat  (None, 64)                256       
 chNormalization)                                                
                                                                 
 dense_2 (Dense)             (None, 64)                4160      
                                                                 
 batch_normalization_2 (Bat  (None, 64)                2

#### Configure model

In [11]:
model.compile(loss='categorical_crossentropy', optimizer='nadam', metrics=['accuracy'])

#### Train!

In [12]:
model.fit(X_train, y_train, batch_size=128, epochs=20, verbose=1, validation_data=(X_valid, y_valid))

Epoch 1/20
469/469 [==============================] - 6s 8ms/step - loss: 0.3990 - accuracy: 0.8800 - val_loss: 0.1669 - val_accuracy: 0.9493
Epoch 2/20
469/469 [==============================] - 3s 5ms/step - loss: 0.1525 - accuracy: 0.9557 - val_loss: 0.1159 - val_accuracy: 0.9637
Epoch 3/20
469/469 [==============================] - 2s 5ms/step - loss: 0.1103 - accuracy: 0.9656 - val_loss: 0.1159 - val_accuracy: 0.9649
Epoch 4/20
469/469 [==============================] - 2s 5ms/step - loss: 0.0919 - accuracy: 0.9715 - val_loss: 0.1032 - val_accuracy: 0.9695
Epoch 5/20
469/469 [==============================] - 3s 6ms/step - loss: 0.0774 - accuracy: 0.9761 - val_loss: 0.0995 - val_accuracy: 0.9699
Epoch 6/20
469/469 [==============================] - 2s 4ms/step - loss: 0.0656 - accuracy: 0.9790 - val_loss: 0.0920 - val_accuracy: 0.9717
Epoch 7/20
469/469 [==============================] - 2s 5ms/step - loss: 0.0570 - accuracy: 0.9815 - val_loss: 0.1026 - val_accuracy: 0.9684
Epoch 

#### Performing inference

In [13]:
valid_0 = X_valid[0].reshape(1, 784)

In [14]:
model.predict(valid_0)

1/1 [==============================] - 0s 122ms/step


array([[5.0910289e-06, 1.1748543e-07, 3.0548415e-07, 1.1457006e-06,
        6.3599367e-07, 5.8431500e-09, 2.9439109e-08, 9.9996626e-01,
        8.0438966e-08, 2.6225462e-05]], dtype=float32)

In [12]:
# model.predict_classes(valid_0)

In [15]:
# The predict_classes() method no longer exists in recent TensorFlow releases. 
# Instead you could use:
import numpy as np
np.argmax(model.predict(valid_0), axis=-1)

1/1 [==============================] - 0s 26ms/step


array([7], dtype=int64)