# Regression Example in TensorFlow (with TensorBoard)
Predicting house prices in Boston, Massachusetts while logging results for TensorBoard

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jonkrohn/DLTFpT/blob/master/notebooks/regression_in_tensorflow_with_tensorboard.ipynb)

#### Load dependencies

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import boston_housing 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 
from tensorflow.keras.callbacks import ModelCheckpoint 
from tensorflow.keras.callbacks import TensorBoard # new!  
import os 

#### Load data

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

#### Design neural network architecture

In [7]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Dense(1, activation='linear')) #linear because we are predicting a continuous variable

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                448       
                                                                 
 batch_normalization (Batch  (None, 32)                128       
 Normalization)                                                  
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 batch_normalization_1 (Bat  (None, 16)                64        
 chNormalization)                                                
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 1

#### Configure Model

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam', )

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_50'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.hdf5', # decimal integers
                                  save_weights_only=True) # otherwise full model is saved

In [14]:
tensorboard = TensorBoard(log_dir='logs/' + run_name)
# sess.graph contains the graph definition; that enables the Graph Visualizer.

#file_writer = tf.summary.FileWriter('logs/', sess.graph)

AttributeError: module 'tensorboard.summary._tf.summary' has no attribute 'FileWriter'

#### Train!

In [ ]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint, tensorboard]) 

Epoch 1/32


51/51 [==============================] - 1s 6ms/step - loss: 574.2991 - val_loss: 615.3801
Epoch 2/32
51/51 [==============================] - 0s 3ms/step - loss: 558.2911 - val_loss: 602.2886
Epoch 3/32
51/51 [==============================] - 0s 3ms/step - loss: 543.6044 - val_loss: 574.1384
Epoch 4/32
51/51 [==============================] - 0s 3ms/step - loss: 530.6501 - val_loss: 550.9173
Epoch 5/32
51/51 [==============================] - 0s 3ms/step - loss: 511.7399 - val_loss: 546.2864
Epoch 6/32
51/51 [==============================] - 0s 3ms/step - loss: 497.3950 - val_loss: 526.9281
Epoch 7/32
51/51 [==============================] - 0s 3ms/step - loss: 474.4537 - val_loss: 480.3800
Epoch 8/32
51/51 [==============================] - 0s 3ms/step - loss: 444.2628 - val_loss: 455.2715
Epoch 9/32
51/51 [==============================] - 0s 3ms/step - loss: 424.3246 - val_loss: 439.1710
Epoch 10/32
51/51 [==============================] - 0s 3ms/step - loss: 389.7624 - val_loss:

#### Performing inference

In [ ]:
model.load_weights(output_path + '/weights.31.hdf5')

In [ ]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [ ]:
y_valid[42]

14.1

In [ ]:
model.predict(np.reshape(X_valid[42], [1, 13]))

1/1 [==============================] - 0s 182ms/step


array([[13.857501]], dtype=float32)